site_name: "The Birds, the Bees, and the Awkward Conversations"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate
nav:
  - index.md
  - general-tips.md
  - guides/early-childhood.md
  - guides/early-school-age.md
  - guides/preteens.md
  - guides/teenagers.md
extensions:
  - emoji

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

extra:
  generator: false
